services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - DB_PATH=/app/data/api_data.db
      - FRONTEND_ADDRESS=http://localhost:3001
    volumes:
      - ./backend:/app
      - ./data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    environment:
      - NUXT_PUBLIC_BASE_API=http://localhost:8001
