services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/app/data/api_data.db
    volumes:
      - ./backend:/app
      - ./data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - NUXT_API_URL=http://backend:8000
